import { Inter } from "next/font/google";
import "./globals.css";
import localfont from "next/font/local";

const poppinsRegular = localfont({
  src: [
    {
      path: "../public/fonts/Poppins-Regular.ttf",
    },
  ],
  variable: "--font-poppinsRegular",
});

const poppinsMedium = localfont({
  src: [
    {
      path: "../public/fonts/Poppins-Medium.ttf",
    },
  ],
  variable: "--font-poppinsMedium",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppinsRegular.variable} ${poppinsMedium.variable} font-poppinsRegular `}
      >
        <main className="max-w-full overflow-hidden min-h-screen bg-white text-secondary">
          {children}
        </main>
      </body>
    </html>
  );
}
