import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import WillBeDeleted from "@/components/WillBeDeleted";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const inter = Inter({
  subsets: ["latin"],

  variable: "--font-inter",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${poppins.variable} font-poppins `}>
        <main className="overflow-hidden">
          <WillBeDeleted />

          {children}
        </main>
      </body>
    </html>
  );
}
